// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: api/proto/cluster_status.proto

package gopherloadv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterId         string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ActiveConnections int64                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	Region            string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	MaxConnections    int64                  `protobuf:"varint,4,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	ObservedAtUnix    int64                  `protobuf:"varint,5,opt,name=observed_at_unix,json=observedAtUnix,proto3" json:"observed_at_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoadReport) Reset() {
	*x = LoadReport{}
	mi := &file_api_proto_cluster_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadReport) ProtoMessage() {}

func (x *LoadReport) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadReport.ProtoReflect.Descriptor instead.
func (*LoadReport) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_status_proto_rawDescGZIP(), []int{0}
}

func (x *LoadReport) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *LoadReport) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *LoadReport) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LoadReport) GetMaxConnections() int64 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *LoadReport) GetObservedAtUnix() int64 {
	if x != nil {
		return x.ObservedAtUnix
	}
	return 0
}

type LoadAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TotalLoad     int64                  `protobuf:"varint,3,opt,name=total_load,json=totalLoad,proto3" json:"total_load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadAck) Reset() {
	*x = LoadAck{}
	mi := &file_api_proto_cluster_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAck) ProtoMessage() {}

func (x *LoadAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_cluster_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAck.ProtoReflect.Descriptor instead.
func (*LoadAck) Descriptor() ([]byte, []int) {
	return file_api_proto_cluster_status_proto_rawDescGZIP(), []int{1}
}

func (x *LoadAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *LoadAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoadAck) GetTotalLoad() int64 {
	if x != nil {
		return x.TotalLoad
	}
	return 0
}

var File_api_proto_cluster_status_proto protoreflect.FileDescriptor

const file_api_proto_cluster_status_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/cluster_status.proto\x12\rgopherload.v1\"\xc5\x01\n" +
	"\n" +
	"LoadReport\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x03R\x11activeConnections\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12'\n" +
	"\x0fmax_connections\x18\x04 \x01(\x03R\x0emaxConnections\x12(\n" +
	"\x10observed_at_unix\x18\x05 \x01(\x03R\x0eobservedAtUnix\"^\n" +
	"\aLoadAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"total_load\x18\x03 \x01(\x03R\ttotalLoad2P\n" +
	"\rClusterStatus\x12?\n" +
	"\n" +
	"ReportLoad\x12\x19.gopherload.v1.LoadReport\x1a\x16.gopherload.v1.LoadAckB4Z2github.com/ciara/gopherload/api/proto;gopherloadv1b\x06proto3"

var (
	file_api_proto_cluster_status_proto_rawDescOnce sync.Once
	file_api_proto_cluster_status_proto_rawDescData []byte
)

func file_api_proto_cluster_status_proto_rawDescGZIP() []byte {
	file_api_proto_cluster_status_proto_rawDescOnce.Do(func() {
		file_api_proto_cluster_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_cluster_status_proto_rawDesc), len(file_api_proto_cluster_status_proto_rawDesc)))
	})
	return file_api_proto_cluster_status_proto_rawDescData
}

var file_api_proto_cluster_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_cluster_status_proto_goTypes = []any{
	(*LoadReport)(nil), // 0: gopherload.v1.LoadReport
	(*LoadAck)(nil),    // 1: gopherload.v1.LoadAck
}
var file_api_proto_cluster_status_proto_depIdxs = []int32{
	0, // 0: gopherload.v1.ClusterStatus.ReportLoad:input_type -> gopherload.v1.LoadReport
	1, // 1: gopherload.v1.ClusterStatus.ReportLoad:output_type -> gopherload.v1.LoadAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_cluster_status_proto_init() }
func file_api_proto_cluster_status_proto_init() {
	if File_api_proto_cluster_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_cluster_status_proto_rawDesc), len(file_api_proto_cluster_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_cluster_status_proto_goTypes,
		DependencyIndexes: file_api_proto_cluster_status_proto_depIdxs,
		MessageInfos:      file_api_proto_cluster_status_proto_msgTypes,
	}.Build()
	File_api_proto_cluster_status_proto = out.File
	file_api_proto_cluster_status_proto_goTypes = nil
	file_api_proto_cluster_status_proto_depIdxs = nil
}
