// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.26.1
// source: api/proto/cluster_status.proto

package gopherloadv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterStatus_ReportLoad_FullMethodName = "/gopherload.v1.ClusterStatus/ReportLoad"
)

// ClusterStatusClient is the client API for ClusterStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClusterStatus reports load metrics from clusters to the balancer.
type ClusterStatusClient interface {
	ReportLoad(ctx context.Context, in *LoadReport, opts ...grpc.CallOption) (*LoadAck, error)
}

type clusterStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterStatusClient(cc grpc.ClientConnInterface) ClusterStatusClient {
	return &clusterStatusClient{cc}
}

func (c *clusterStatusClient) ReportLoad(ctx context.Context, in *LoadReport, opts ...grpc.CallOption) (*LoadAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadAck)
	err := c.cc.Invoke(ctx, ClusterStatus_ReportLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterStatusServer is the server API for ClusterStatus service.
// All implementations must embed UnimplementedClusterStatusServer
// for forward compatibility.
//
// ClusterStatus reports load metrics from clusters to the balancer.
type ClusterStatusServer interface {
	ReportLoad(context.Context, *LoadReport) (*LoadAck, error)
	mustEmbedUnimplementedClusterStatusServer()
}

// UnimplementedClusterStatusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterStatusServer struct{}

func (UnimplementedClusterStatusServer) ReportLoad(context.Context, *LoadReport) (*LoadAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportLoad not implemented")
}
func (UnimplementedClusterStatusServer) mustEmbedUnimplementedClusterStatusServer() {}
func (UnimplementedClusterStatusServer) testEmbeddedByValue()                       {}

// UnsafeClusterStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterStatusServer will
// result in compilation errors.
type UnsafeClusterStatusServer interface {
	mustEmbedUnimplementedClusterStatusServer()
}

func RegisterClusterStatusServer(s grpc.ServiceRegistrar, srv ClusterStatusServer) {
	// If the following call panics, it indicates UnimplementedClusterStatusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterStatus_ServiceDesc, srv)
}

func _ClusterStatus_ReportLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterStatusServer).ReportLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClusterStatus_ReportLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterStatusServer).ReportLoad(ctx, req.(*LoadReport))
	}
	return interceptor(ctx, in, info, handler)
}

// ClusterStatus_ServiceDesc is the grpc.ServiceDesc for ClusterStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gopherload.v1.ClusterStatus",
	HandlerType: (*ClusterStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportLoad",
			Handler:    _ClusterStatus_ReportLoad_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/cluster_status.proto",
}
